config/routes.rb
Dashboard::Application.routes.draw do
  resources :data_points

  resources :perspectives do
    member do
      post 'watch'
    end
  end

  resources :entries

  # Sample of named route:
  #   match 'products/:id/purchase' => 'catalog#purchase', :as => :purchase
  # This route can be invoked with purchase_url(:id => product.id)

  # Sample resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Sample resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Sample resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Sample resource route with more complex sub-resources
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', :on => :collection
  #     end
  #   end

  # Sample resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end


  root :to => "dashboard#index"

  post '/dashboard', { :to => 'dashboard#multi_create' }
end

app/models/data_point.rb
class DataPoint < ActiveRecord::Base
  attr_accessor :perspective
  
  def self.current
    find_by_sql("SELECT d1.*
FROM `data_points` d1,
  (SELECT MAX(recorded_at) AS max_recorded_at, family, name
FROM `data_points` d2
GROUP BY family,`name`) a1
WHERE a1.max_recorded_at = d1.recorded_at AND d1.family = a1.family AND d1.name = a1.name")
  end

  def self.families
    connection.select_all("SELECT DISTINCT(family) FROM data_points").map {|x| x['family'] }
  end

  def self.names
    connection.select_all("SELECT DISTINCT(name) FROM data_points").map {|x| x['name'] }
  end

  def self.from_couch(obj)
    recorded_at = Time.at obj.delete('time_code')
    family      = obj.delete('collection')
    obj.delete('_id')
    obj.delete('_rev')

    name = obj.keys.first

    value_num = obj[name]
    value_str = obj[name]

    if value_num.to_i.to_s == value_num.to_s
      value_num = value_num.to_i
    else
      value_num = nil
    end
    
    new({
          :recorded_at => recorded_at,
          :family => family,
          :name => name,
          :value_num => value_num,
          :value_str => value_str
        })
  end

  def self.save(family, name, value, recorded_at)
    value_num = value
    value_str = value

    if value_num.to_i.to_s == value_num.to_s
      value_num = value_num.to_i
    else
      value_num = nil
    end

    attributes = {
      :family      => family,
      :name        => name,
      :value_num   => value_num,
      :value_str   => value_str,
      :recorded_at => recorded_at
    }
    
    new(attributes).save!
  end

  def sampled_history
    @sampled_history ||= perspective.sparkline_data.select do |sparkline_row|
      name == sparkline_row['name'] && family == sparkline_row['family']
    end.map do |sparkline_row|
      sparkline_row['avg'].to_i
    end
  end

  def high
    @sampled_history.max
  end

  def low
    @sampled_history.min
  end

  def value
    value_num || value_str
  end

  def numerical?
    !!value_num
  end
end

app/controllers/data_points_controller.rb
class DataPointsController < ApplicationController
  before_filter :require_http_authentication

  def new
    @data_point = DataPoint.new
  end

  def create
    DataPoint.save(params[:data_point][:family],
                   params[:data_point][:name],
                   params[:value],
                   Time.new)
    redirect_to '/'
  end
end

app/helpers/data_points_helper.rb
module DataPointsHelper
end

app/views/data_points/_form.html.erb
<%= form_for(@data_point) do |f| %>
  <% if @data_point.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@data_point.errors.count, "error") %> prohibited this data_point from being saved:</h2>

      <ul>
      <% @data_point.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :family %><br />
    <%= f.text_field :family %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <label>Value<br />
      <input type="text" name="value" />
    </label>

  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/data_points/edit.html.erb
<h1>Editing data_point</h1>

<%= render 'form' %>

<%= link_to 'Show', @data_point %> |
<%= link_to 'Back', data_points_path %>

app/views/data_points/index.html.erb
<h1>Listing data_points</h1>

<table>
  <tr>
    <th>Family</th>
    <th>Name</th>
    <th>Value num</th>
    <th>Value str</th>
    <th>Recorded at</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @data_points.each do |data_point| %>
  <tr>
    <td><%= data_point.family %></td>
    <td><%= data_point.name %></td>
    <td><%= data_point.value_num %></td>
    <td><%= data_point.value_str %></td>
    <td><%= data_point.recorded_at %></td>
    <td><%= link_to 'Show', data_point %></td>
    <td><%= link_to 'Edit', edit_data_point_path(data_point) %></td>
    <td><%= link_to 'Destroy', data_point, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Data point', new_data_point_path %>

app/views/data_points/new.html.erb
<h1>New data_point</h1>

<%= render 'form' %>

<%= link_to 'Back', data_points_path %>

<script>
  $(function() {
    var families = <%= DataPoint.families.to_json.html_safe %>;
    var names = <%= DataPoint.names.to_json.html_safe %>;

    $('#data_point_family').autocomplete({ source: families });
    $('#data_point_name').autocomplete({ source: names });
  });
</script>

app/views/data_points/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Family:</b>
  <%= @data_point.family %>
</p>

<p>
  <b>Name:</b>
  <%= @data_point.name %>
</p>

<p>
  <b>Value num:</b>
  <%= @data_point.value_num %>
</p>

<p>
  <b>Value str:</b>
  <%= @data_point.value_str %>
</p>

<p>
  <b>Recorded at:</b>
  <%= @data_point.recorded_at %>
</p>


<%= link_to 'Edit', edit_data_point_path(@data_point) %> |
<%= link_to 'Back', data_points_path %>