config/routes.rb
Dashboard::Application.routes.draw do
  resources :data_points

  resources :perspectives do
    member do
      post 'watch'
    end
  end

  resources :entries

  # Sample of named route:
  #   match 'products/:id/purchase' => 'catalog#purchase', :as => :purchase
  # This route can be invoked with purchase_url(:id => product.id)

  # Sample resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Sample resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Sample resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Sample resource route with more complex sub-resources
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', :on => :collection
  #     end
  #   end

  # Sample resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end


  root :to => "dashboard#index"

  post '/dashboard', { :to => 'dashboard#multi_create' }
end

app/models/perspective.rb
class Perspective < ActiveRecord::Base
  has_many :memberships
  def data_points
    @data_points ||= begin
                       all_points = DataPoint.current.select { |data_point| show? data_point }
                       all_points.each { |data_point| data_point.perspective = self }
                       all_points
                     end
  end

  def non_featured_data_points
    data_points.reject { |x| feature? x }
  end

  def featured_data_points
    data_points.select { |x| feature? x }
  end

  def grouped_data_points
    non_featured_data_points.group_by &:family
  end

  def show?(data_point)
    !! memberships.find_by_family_and_name(data_point.family, data_point.name)
  end

  def feature?(data_point)
    x = memberships.find_by_family_and_name(data_point.family, data_point.name)
    x && x.featured?
  end

  def preload
    sparkline_data
  end

  def self.data_cache
    $perspective_data_cache ||= {}
  end

  def recache_data
    self.class.data_cache[self.id] = sparkline_query_result
  end

  def sparkline_data
    self.class.data_cache[self.id] ||= sparkline_query_result
  end

  def sparkline_query_result
    self.class.connection.select_all <<-EOQUERY
      SELECT dp1.*, bin_query.*, ((dp1.recorded_at - bin_query.min_r) DIV bin_query.range_r) as bin, AVG(dp1.value_num) as avg
      FROM data_points dp1,
          (SELECT ((range_query.max_r - range_query.min_r) DIV #{self.class.data_points_per_graph}) as range_r, range_query.min_r, range_query.family, range_query.name
            FROM (SELECT MIN(dp.recorded_at) as min_r, MAX(dp.recorded_at) as max_r, dp.family, dp.name
                  FROM `data_points` dp
                  WHERE dp.value_num IS NOT NULL
                  GROUP BY dp.family, dp.name) range_query) bin_query
      WHERE dp1.value_num IS NOT NULL
        AND dp1.family = bin_query.family
        AND dp1.name = bin_query.name
      GROUP BY bin, dp1.family, dp1.name
      ORDER BY dp1.recorded_at
    EOQUERY
  end

  def self.data_points_per_graph
    100
  end
end

app/controllers/perspectives_controller.rb
class PerspectivesController < ApplicationController
  before_filter :require_http_authentication
  
  # GET /perspectives
  # GET /perspectives.xml
  def index
    @perspectives = Perspective.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @perspectives }
    end
  end

  # GET /perspectives/1
  # GET /perspectives/1.xml
  def show
    @perspective = Perspective.find(params[:id])
    @perspective.preload
    respond_to do |format|
      format.html { render :layout => false }
      format.json { render :json => @perspective.data_points }
      format.xml  { render :xml => @perspective.data_points }
    end
  end
  after_filter :recache, :only => 'show'

  def recache
    # recache for next time
    @perspective.recache_data
  end

  # GET /perspectives/new
  # GET /perspectives/new.xml
  def new
    @perspective = Perspective.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @perspective }
    end
  end

  # GET /perspectives/1/edit
  def edit
    @perspective = Perspective.find(params[:id])
  end

  # POST /perspectives
  # POST /perspectives.xml
  def create
    @perspective = Perspective.new(params[:perspective])

    respond_to do |format|
      if @perspective.save
        format.html { redirect_to(@perspective, :notice => 'Perspective was successfully created.') }
        format.xml  { render :xml => @perspective, :status => :created, :location => @perspective }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @perspective.errors, :status => :unprocessable_entity }
      end
    end
  end

  def watch
    self.current_perspective = Perspective.find(params[:id])
    redirect_to '/'
  end

  # PUT /perspectives/1
  # PUT /perspectives/1.xml
  def update
    @perspective = Perspective.find(params[:id])

    respond_to do |format|
      if @perspective.update_attributes(params[:perspective])

        features = (params[:data_point] && params[:data_point][:features]) || []

        if params[:data_point] && params[:data_point][:memberships]
          memberships = []

          params[:data_point][:memberships].each do |membership|
            featured     = features.include? membership
            family, name = membership.split("|||")
            memberships << Membership.new({ :family => family, :name => name, :featured => featured })
          end

          @perspective.memberships = memberships
          @perspective.save!
        end
        format.html { redirect_to(@perspective, :notice => 'Perspective was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @perspective.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /perspectives/1
  # DELETE /perspectives/1.xml
  def destroy
    @perspective = Perspective.find(params[:id])
    @perspective.destroy

    respond_to do |format|
      format.html { redirect_to(perspectives_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/perspectives_helper.rb
module PerspectivesHelper
end

app/views/perspectives/_form.html.erb
<%= form_for(@perspective) do |f| %>
  <% if @perspective.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@perspective.errors.count, "error") %> prohibited this perspective from being saved:</h2>

      <ul>
      <% @perspective.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>

  <div class="entries">
    <table>
      <tr>
        <th>Family</th>
        <th>Name</th>
        <th>Show</th>
        <th>Feature</th>
      </tr>
      <% DataPoint.current.each do |dp| %>
      <tr>
        <td><%= dp.family.titleize %></td>
        <td><%= dp.name.titleize %></td>
        <td><%= show_data_point_check_box @perspective, dp %></td>
        <td><%= feature_data_point_check_box @perspective, dp %></td>
      </tr>
      <% end %>
    </table>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/perspectives/edit.html.erb
<h1>Editing perspective</h1>

<%= render 'form' %>

<%= link_to 'Show', @perspective %> |
<%= link_to 'Back', perspectives_path %>

app/views/perspectives/index.html.erb
<h1>Listing perspectives</h1>

<table>
  <tr>
    <th></th>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @perspectives.each do |perspective| %>
  <tr>
    <td><%= button_to 'Set as Default', watch_perspective_path(perspective), :method => 'post' %></td>
    <td><%= perspective.name %></td>
    <td><%= link_to 'Show', perspective %></td>
    <td><%= link_to 'Edit', edit_perspective_path(perspective) %></td>
    <td><%= link_to 'Destroy', perspective, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Perspective', new_perspective_path %>

app/views/perspectives/new.html.erb
<h1>New perspective</h1>

<%= render 'form' %>

<%= link_to 'Back', perspectives_path %>

app/views/perspectives/show.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Dash</title>
    <%= stylesheet_link_tag 'dashboard' %>
    <%= javascript_include_tag :defaults %>
    <%= javascript_include_tag 'jquery.masonry.min' %>
    <%= javascript_include_tag 'jquery.sparkline.min' %>
    <%= javascript_include_tag 'dashboard' %>

    <meta http-equiv="refresh" content="120">
  </head>
  <body>
    <div id="wrapper">

      <div class="featured">
        <dl>
          <% @perspective.featured_data_points.each do |dp| %>
            <dt><%= dp.family.titleize %> <%= dp.name.titleize %></dt>
            <% if dp.numerical? %>
              <dd>
                <div>
                <span class="sparkline"><%= dp.sampled_history.join(",") %></span>
                <span class="number current"><%= dp.value %></span>
                <span class="number high"><%= dp.high %></span>
                <span class="number low"><%= dp.low %></span>
                </div>
              </dd>
            <% else %>
              <dd><%= dp.value %></dd>
            <% end %>
          <% end %>
        </dl>
      </div>

      <div id="nonfeatured">
        <% @perspective.grouped_data_points.each do |family, data_points| %>

          <div class="nonfeatured">
            <h2><%= family.titleize %></h2>
            <dl>
              <% data_points.each do |dp| %>
                <dt><%= dp.name.titleize %></dt>
                <% if dp.numerical? %>
                  <dd>
                    <span class="sparkline"><%= dp.sampled_history.join(",") %></span>
                    <span class="number"><%= dp.value %></span>
                  </dd>
                <% else %>
                  <dd><%= dp.value %></dd>
                <% end %>
              <% end %>
            </dl>
          </div>
        <% end %>
      </div>
    </div>

    <footer>
      <ul>
        <li><%= link_to "Edit Perspective", edit_perspective_path(@perspective) %></li>
        <li><%= link_to "Perspectives", perspectives_path %></li>
        <li><%= link_to "Update Number", new_data_point_path %></li>
      </ul>
      <div class="clearall"></div>
    </footer>
  </body>
</html>